2021-09-28 21:57:23,681 INFO    Thread-2  :26413 [wandb_setup.py:_flush():69] setting env: {'project': 'Active_sweep', 'entity': 'pranbk', 'root_dir': '/home/praneeth/projects/thesis/git/PLDepth/pldepth/hyperopt', 'sweep_id': 'cxz0imm0', 'run_id': 'ixog2vdg', 'sweep_param_path': '/home/praneeth/projects/thesis/git/PLDepth/pldepth/hyperopt/wandb/sweep-cxz0imm0/config-ixog2vdg.yaml'}
2021-09-28 21:57:23,681 INFO    Thread-2  :26413 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-28 21:57:23,682 INFO    Thread-2  :26413 [wandb_init.py:_log_setup():348] Logging user logs to /home/praneeth/projects/thesis/git/PLDepth/pldepth/hyperopt/wandb/run-20210928_215723-ixog2vdg/logs/debug.log
2021-09-28 21:57:23,682 INFO    Thread-2  :26413 [wandb_init.py:_log_setup():349] Logging internal logs to /home/praneeth/projects/thesis/git/PLDepth/pldepth/hyperopt/wandb/run-20210928_215723-ixog2vdg/logs/debug-internal.log
2021-09-28 21:57:23,682 INFO    Thread-2  :26413 [wandb_init.py:init():381] calling init triggers
2021-09-28 21:57:23,682 INFO    Thread-2  :26413 [wandb_init.py:init():388] wandb.init called with sweep_config: {'batch_size': 4, 'epochs': 6, 'lr': 0.0015575547735967904, 'lr_multi': 0.4402191245536155, 'ranking_size': 5, 'rpi': 50}
config: {}
2021-09-28 21:57:23,682 INFO    Thread-2  :26413 [wandb_init.py:init():430] starting backend
2021-09-28 21:57:23,682 INFO    Thread-2  :26413 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-28 21:57:23,694 INFO    Thread-2  :26413 [backend.py:ensure_launched():135] starting backend process...
2021-09-28 21:57:23,701 INFO    Thread-2  :26413 [backend.py:ensure_launched():140] started backend process with pid: 26441
2021-09-28 21:57:23,702 INFO    Thread-2  :26413 [wandb_init.py:init():435] backend started and connected
2021-09-28 21:57:23,703 INFO    Thread-2  :26413 [wandb_run.py:_config_callback():847] config_cb None None {'batch_size': 4, 'epochs': 6, 'lr': 0.0015575547735967904, 'lr_multi': 0.4402191245536155, 'ranking_size': 5, 'rpi': 50}
2021-09-28 21:57:23,704 INFO    Thread-2  :26413 [wandb_init.py:init():494] updated telemetry
2021-09-28 21:57:23,704 INFO    Thread-2  :26413 [wandb_init.py:init():517] communicating current version
2021-09-28 21:57:24,426 INFO    Thread-2  :26413 [wandb_init.py:init():522] got version response 
2021-09-28 21:57:24,427 INFO    Thread-2  :26413 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-28 21:57:24,798 INFO    Thread-2  :26413 [wandb_init.py:init():557] starting run threads in backend
2021-09-28 21:57:28,553 INFO    Thread-2  :26413 [wandb_run.py:_console_start():1605] atexit reg
2021-09-28 21:57:28,553 INFO    Thread-2  :26413 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-09-28 21:57:28,554 INFO    Thread-2  :26413 [wandb_run.py:_redirect():1484] Redirecting console.
2021-09-28 21:57:28,554 ERROR   Thread-2  :26413 [wandb_run.py:_redirect():1543] Failed to redirect.
Traceback (most recent call last):
  File "/home/praneeth/anaconda3/envs/thesis/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1536, in _redirect
    out_redir.install()
  File "/home/praneeth/anaconda3/envs/thesis/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/praneeth/anaconda3/envs/thesis/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/home/praneeth/anaconda3/envs/thesis/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/praneeth/anaconda3/envs/thesis/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2021-09-28 21:57:28,555 INFO    Thread-2  :26413 [wandb_init.py:init():582] run started, returning control to user process
2021-09-28 21:57:28,556 INFO    Thread-2  :26413 [wandb_run.py:finish():1275] finishing run pranbk/Active_sweep/ixog2vdg
